Task/t 14452 add relay meter helm chart
pokt-foundation/charts pull request #70
Opened 2022-11-07 10:58 UTC by rutwickjain87

Helm chart to deploy POKT Relay Meter service on EKS

2022-11-07 15:08 UTC, WesleyCharlesBlake requested changes
there a bit that needs changing here. I'll push some changes in a bit

2022-11-07 15:08 UTC, WesleyCharlesBlake commented on charts/pokt-relay-meter/values.yaml
> +    repository: 059424750518.dkr.ecr.us-west-2.amazonaws.com/relay-meter-collector
use `pocketfoundation/relay-meter` when its pushed

2022-11-07 15:08 UTC, WesleyCharlesBlake commented on charts/pokt-relay-meter/values.yaml
> +    tag: "latest"
I would leave this blank, and then set the appVersion in Charts.yaml to match the semver tag

2022-11-14 11:55 UTC, WesleyCharlesBlake submitted a review, later dismissed
LGTM, just change the container name for the test-connection pod to something more applicable

2022-11-14 11:55 UTC, WesleyCharlesBlake commented on charts/pokt-relay-meter/templates/tests/test-connection.yaml
> +    - name: wget
change the container name to `nc`

2022-11-14 11:57 UTC, rutwickjain87 commented on charts/pokt-relay-meter/templates/tests/test-connection.yaml
> +    - name: wget
fixed

2022-11-14 12:53 UTC, WesleyCharlesBlake approved these changes

2022-11-14 12:53 UTC, merged